org: '1305580506'
app: sticky-notes
stage: prod
component: layer
name: sticky-notes-layer
inputs:
  name: sticky-notes-layer
  region: ap-beijing
  src:
    src: ../node_modules
    targetDir: /node_modules
  runtimes:
    - Nodejs12.16
