component: http
name: http-express-y7japkl_wx
inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    framework: express
    name: '${name}'
    runtime: Nodejs12.16
    eip: false
    timeout: 3
    memorySize: 512
    tags: []
    environments: []
    layers:
      - name: '${output:${stage}:${app}:sticky-notes-layer.name}'
        version: '${output:${stage}:${app}:sticky-notes-layer.version}'
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains: []
  region: ap-beijing
  isAutoCiDeploy: false
org: '1305580506'
app: sticky-notes
stage: prod
